<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CostEstimates\Validators\**" />
    <Compile Remove="Files\ShareProjectFiles\**" />
    <Compile Remove="Files\ShareProjectFile\**" />
    <Compile Remove="ProjectCosts\GetProjectCostDetails\**" />
    <Compile Remove="ProjectCosts\ShareProjectCost\**" />
    <Compile Remove="Tenants\UserTenants\**" />
    <Compile Remove="Users\UserActivate\**" />
    <Compile Remove="Users\UserGoogleRegister\**" />
    <Compile Remove="Users\UserLinkGoogle\**" />
    <Compile Remove="Users\UserLogin\**" />
    <Compile Remove="Users\UserLogout\**" />
    <Compile Remove="Users\UserPasswordResetRequest\**" />
    <Compile Remove="Users\UserRefresh\**" />
    <Compile Remove="Users\UserRegister\**" />
    <Compile Remove="Users\UserResetPassword\**" />
    <EmbeddedResource Remove="CostEstimates\Validators\**" />
    <EmbeddedResource Remove="Files\ShareProjectFiles\**" />
    <EmbeddedResource Remove="Files\ShareProjectFile\**" />
    <EmbeddedResource Remove="ProjectCosts\GetProjectCostDetails\**" />
    <EmbeddedResource Remove="ProjectCosts\ShareProjectCost\**" />
    <EmbeddedResource Remove="Tenants\UserTenants\**" />
    <EmbeddedResource Remove="Users\UserActivate\**" />
    <EmbeddedResource Remove="Users\UserGoogleRegister\**" />
    <EmbeddedResource Remove="Users\UserLinkGoogle\**" />
    <EmbeddedResource Remove="Users\UserLogin\**" />
    <EmbeddedResource Remove="Users\UserLogout\**" />
    <EmbeddedResource Remove="Users\UserPasswordResetRequest\**" />
    <EmbeddedResource Remove="Users\UserRefresh\**" />
    <EmbeddedResource Remove="Users\UserRegister\**" />
    <EmbeddedResource Remove="Users\UserResetPassword\**" />
    <None Remove="CostEstimates\Validators\**" />
    <None Remove="Files\ShareProjectFiles\**" />
    <None Remove="Files\ShareProjectFile\**" />
    <None Remove="ProjectCosts\GetProjectCostDetails\**" />
    <None Remove="ProjectCosts\ShareProjectCost\**" />
    <None Remove="Tenants\UserTenants\**" />
    <None Remove="Users\UserActivate\**" />
    <None Remove="Users\UserGoogleRegister\**" />
    <None Remove="Users\UserLinkGoogle\**" />
    <None Remove="Users\UserLogin\**" />
    <None Remove="Users\UserLogout\**" />
    <None Remove="Users\UserPasswordResetRequest\**" />
    <None Remove="Users\UserRefresh\**" />
    <None Remove="Users\UserRegister\**" />
    <None Remove="Users\UserResetPassword\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Business\Business.csproj" />
    <ProjectReference Include="..\Business.AIAgent\Business.AIAgent.csproj" />
    <ProjectReference Include="..\Entities\Entities.csproj" />
    <ProjectReference Include="..\Repositories\Repositories.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Messages\GetProjectMessages\" />
  </ItemGroup>

</Project>
