services:
  webapi:
    container_name: pdm-webapi-development
    build:
      context: ../02-ApplicationServices/ProductDataManagementWebAPI
      dockerfile: ../../03-Deployment/Backend/API/Dockerfile
      args:
        BUILD_CONFIGURATION: Debug
    env_file:
      - ./.env.development
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8080
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    expose:
      - "8080"              # dostępne tylko wewnątrz sieci Dockera
    volumes:
      - ../02-ApplicationServices/ProductDataManagementWebAPI:/src
      - dpkeys:/keys
    restart: always
    command:
      - dotnet
      - watch
      - run
      - --urls
      - http://0.0.0.0:8080

  ui:
    container_name: pdm-ui-development
    build:
      context: ../01-Applications/ProjectDataManagamentUI
      dockerfile: ../../03-Deployment/Frontend/UI/Dockerfile
    expose:
      - "80"               # dostępne tylko wewnątrz sieci Dockera
    restart: always

  nginx:
    container_name: pdm-nginx-development
    image: nginx:alpine
    depends_on:
      - webapi
      - ui
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8085:80"          # NGINX dostępny lokalnie pod portem 8085
    restart: always

volumes:
  dpkeys: {}

# uruchomienie:
# docker compose -p pdm-development -f docker-compose.development.yml up -d --build
